### ISSUE TITLE
VIDIOC_QUERYMENU: Invalid argument

### ISSUE THREAD

**Issue by solbach** [transcendrobotics/zed_cpu_ros#1]
Hi,
thanks for offering this code. I tried to run it and ROS spits out the following message by running either _roslaunch zed_cpu_ros camera_calibration.launch_ or _roslaunch zed_cpu_ros zed_cpu_ros.launch_

>  [ INFO] [1470673522.009342437]: Try to initialize the camera
> VIDIOC_QUERYMENU: Invalid argument
> VIDIOC_QUERYMENU: Invalid argument
> VIDIOC_QUERYMENU: Invalid argument
> VIDIOC_QUERYMENU: Invalid argument
> VIDIOC_QUERYMENU: Invalid argument
> VIDIOC_QUERYMENU: Invalid argument
> VIDIOC_QUERYMENU: Invalid argument

I tried several things. Such as, making sure that opencv is cimpiled wtih libv4l support, libv4l is installed at all, 2 different machines. I can receive a stream with Ubuntu's "Cheese Wevcam Boot" of ZED. 

Would be very nice from you if you could point me into the right direction.

Thanks!

**Comment by willdzeng** [comment]
Hi,

Sorry that I just noticed your post today.

Are you using opencv 2.4 or 3.1?

**Comment by nhanph** [comment]
I get the same problem running the package. My opencv's version is 2.4.8.

**Comment by willdzeng** [comment]
The videoCapture can't set resolution in opencv 2.4, try to use opencv3 if possible.
I will try make 2.4 compatibility.

**Comment by willdzeng** [comment]
Also check out this:
http://stackoverflow.com/questions/21084991/vidioc-querymenu-invalid-argument

**Comment by willdzeng** [comment]
Also you can try comment out
https://github.com/transcendrobotics/zed_cpu_ros/blob/master/src/zed_cpu_ros.cpp#L39

**Comment by nhanph** [comment]
Thanks a lot,

I will try and see if it works. I will let you know.

**Comment by willdzeng** [comment]
Closed due to inactivity, please reopen if the problem still exists.
Thanks.

**Comment by nhanph** [comment]
Hi, the issue was fixed when I update opencv to 2.4.13.

Thank you for the support,
Nhan

**Comment by alirezadir** [comment]
Hi, I have the same issue as @solbach mentioned. I'm using opencv 3.1.0 with ROS indigo on ubuntu 14.04. I tried commenting out setResolution call as well but still getting the error: 
Try to initialize the camera
VIDIOC_QUERYMENU: Invalid argument

Thank you, 
Alireza

**Comment by willdzeng** [comment]
@alirezadir 
Comment out this line also
https://github.com/willdzeng/zed_cpu_ros/blob/master/src/zed_cpu_ros.cpp#L44

**Comment by alirezadir** [comment]
Hi @willdzeng, thanks for the feedback. That issue was fixed, but now ti crashes after loading calibration files. I did some debugging and it seems it's crashing when the  cv::Rodrigues() is called. 

Thank you.
